//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectorMathematic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VectorMathematic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance between vector A &amp; Vector B=.
        /// </summary>
        internal static string distanceEqual {
            get {
                return ResourceManager.GetString("distanceEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Lenght (x)=.
        /// </summary>
        internal static string lenghtEqual {
            get {
                return ResourceManager.GetString("lenghtEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Scalar Multiplication&gt;
        /// Scalar (.
        /// </summary>
        internal static string scalarMultiplicationTitle1 {
            get {
                return ResourceManager.GetString("scalarMultiplicationTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) * Vector .
        /// </summary>
        internal static string scalarMultiplicationTitle2 {
            get {
                return ResourceManager.GetString("scalarMultiplicationTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Vector C.
        /// </summary>
        internal static string scalarMultiplicationTitle3 {
            get {
                return ResourceManager.GetString("scalarMultiplicationTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Square Lenght (x²)=.
        /// </summary>
        internal static string squareLenghtEqual {
            get {
                return ResourceManager.GetString("squareLenghtEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Vector addition&gt; 
        /// Vector A + Vector B = Vector C.
        /// </summary>
        internal static string vectorAdditionTitle {
            get {
                return ResourceManager.GetString("vectorAdditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Vector A&gt;.
        /// </summary>
        internal static string vectorAName {
            get {
                return ResourceManager.GetString("vectorAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Vector B&gt;.
        /// </summary>
        internal static string vectorBName {
            get {
                return ResourceManager.GetString("vectorBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Vector subtraction&gt;
        /// Vector A - Vector B = Vector C.
        /// </summary>
        internal static string vectorSubtractionTitle {
            get {
                return ResourceManager.GetString("vectorSubtractionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  X=.
        /// </summary>
        internal static string xEqual {
            get {
                return ResourceManager.GetString("xEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Y=.
        /// </summary>
        internal static string yEqual {
            get {
                return ResourceManager.GetString("yEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Z=.
        /// </summary>
        internal static string zEqual {
            get {
                return ResourceManager.GetString("zEqual", resourceCulture);
            }
        }
    }
}
